# Generated by Django 3.2.7 on 2021-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
