# Generated by Django 3.2.7 on 2021-09-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprof_followed_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='followed_coins',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
