# Generated by Django 3.2.7 on 2021-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprof_followed_coins'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprof',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='username',
        ),
        migrations.AlterField(
            model_name='userprof',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
